// keeberia caps — keeberia-ninepad-choc — flow 05
// generated by the caps engine; edit the sliders, not the geometry
// cap positions/rows derive from THIS board's pcb (regenerate to change them)

/* [Caps] */
// keycap profile for every cap on the board
profile_id = "dsa"; // [dsa:DSA, cherry:Cherry, oem:OEM, sa:SA, xda:XDA]
// cap wall thickness, mm
wall = 1.5;  // [1:0.1:2.5]
// gap between neighboring caps, mm
cap_gap = 0.5;  // [0.2:0.1:1]
// dish depth multiplier (1 = profile spec)
dish_scale = 1;  // [0.5:0.1:2]
/* [Knob] */
// knob diameter, mm
knob_d = 22;  // [16:1:30]
// knob height above the plate, mm
knob_h = 14;  // [8:1:24]
// d-shaft bore diameter, mm
knob_bore = 6.2;  // [5.5:0.1:7]

/* [Hidden] */
$fn = 48;
// dsa: keycap_playground DSA_keycap module defaults (mm, measured)
// cherry: nur-modkeys PROFILES (h .36u, dish .035u, tilt rad) — viz-grade, calibrate before production
// oem: nur-modkeys PROFILES (h .44u, dish .03u, tilt rad) — viz-grade, calibrate before production
// sa: nur-modkeys PROFILES (h .52u, dish .05u, tilt rad) — viz-grade, calibrate before production
// xda: nur-modkeys PROFILES (h .31u, dish .015u, uniform) — viz-grade, calibrate before production
profiles = [
  ["dsa", 18.41, 0.76, 7.39, 0.8, [0, 0, 0, 0, 0]],
  ["cherry", 18, 0.76, 6.9, 0.67, [-4.9, -2.6, 0, 2.9, 4.3]],
  ["oem", 18, 0.78, 8.4, 0.57, [-4, -2, 0, 2.3, 3.4]],
  ["sa", 18, 0.7, 9.9, 0.95, [-5.7, -2.9, 0, 2.9, 5.4]],
  ["xda", 18, 0.9, 5.9, 0.29, [0, 0, 0, 0, 0]],
];
function prof(id) = [for (p = profiles) if (p[0] == id) p][0];
prof_v = prof(profile_id);
// [x, y, unit_span, row] per cap — from the pcb placements
caps = [
  [-19.05, -30.725, 1, 0],  // SW1
  [0, -30.725, 1, 0],  // SW2
  [19.05, -30.725, 1, 0],  // SW3
  [-19.05, -11.675, 1, 1],  // SW4
  [0, -11.675, 1, 1],  // SW5
  [19.05, -11.675, 1, 1],  // SW6
  [-19.05, 7.375, 1, 2],  // SW7
  [0, 7.375, 1, 2],  // SW8
  [19.05, 7.375, 1, 2],  // SW9
];
knobs = [
];

module rbox2d(w, d, r) {
  offset(r) offset(-r) square([w, d], center = true);
}

// one keycap: tapered hollow body, spherical dish, mx cross stem
module keycap(unit, row) {
  base_w = prof_v[1] * unit - cap_gap;
  top_w = base_w * prof_v[2];
  h = prof_v[3];
  dish = prof_v[4] * dish_scale;
  tilt = prof_v[5][min(row, 4)];
  wall_v = wall;
  difference() {
    // body: hull from the base square to the tilted top square
    hull() {
      linear_extrude(0.01) rbox2d(base_w, base_w, 1.2);
      translate([0, 0, h]) rotate([tilt, 0, 0]) linear_extrude(0.01) rbox2d(top_w, top_w, 1.0);
    }
    // hollow inside: same hull, shrunk by the wall
    translate([0, 0, wall_v]) hull() {
      translate([0, 0, -wall_v]) linear_extrude(0.01) rbox2d(base_w - 2 * wall_v, base_w - 2 * wall_v, 1.0);
      translate([0, 0, h - wall_v]) rotate([tilt, 0, 0]) linear_extrude(0.01) rbox2d(top_w - 2 * wall_v, top_w - 2 * wall_v, 0.8);
    }
    // dish: sphere carved into the tilted top
    translate([0, -top_w * sin(tilt) / 4, h + 24.2 - dish]) rotate([tilt, 0, 0]) sphere(24);
  }
  // mx cross stem socket, inside the cap: ring + cross void + wall bridges
  // (4.1mm cross standard; insertion depth + tolerance pattern from
  // keycap_playground stem defaults)
  cross_w = 4.1;
  cross_t = 1.2;
  depth = 4;
  tol = 0.2;
  difference() {
    cylinder(h = depth, d = 5.6);
    translate([0, 0, -0.5]) union() {
      cube([cross_w - 2 * tol, cross_t - 2 * tol, depth + 1.2], center = true);
      cube([cross_t - 2 * tol, cross_w - 2 * tol, depth + 1.2], center = true);
    }
  }
  // bridges: tie the stem ring to the inner cap walls so it prints
  bridge_len = (base_w - 2 * wall_v) / 2;
  for (ang = [0, 90, 180, 270]) {
    rotate([0, 0, ang]) translate([2.0, -0.4, depth / 2]) cube([bridge_len, 0.8, 0.8]);
  }
}

// knob cover: ridged cylinder with a d-shaft bore
module knob() {
  difference() {
    union() {
      cylinder(h = knob_h, d1 = knob_d, d2 = knob_d - 3);
      for (i = [0 : 24]) {
        rotate([0, 0, i * 15]) translate([(knob_d - 1.8) / 2, 0, 1.2]) cube([1.4, 2.2, knob_h - 2.4]);
      }
    }
    translate([0, 0, -0.5]) {
      cylinder(h = knob_h - 2.5, d = knob_bore);
      translate([0, -knob_bore / 2 - 0.2, 0]) cube([knob_bore / 2 + 0.2, knob_bore + 0.4, knob_h - 2.5]);
    }
  }
}

for (c = caps) {
  translate([c[0], c[1], 0]) keycap(c[2], c[3]);
}
for (k = knobs) {
  translate([k[0], k[1], 0]) knob();
}