// keeberia-ninepad-choc — case
// generated by keeberia from the project model. edit any parameter
// below and re-render: the model is parametric and dependency-free
// (vanilla openscad, no libraries — paste it into any customizer or
// makerlab configurator and the sliders just appear). coordinates match
// the pcb's board coordinates: (0,0) is the center, +y = usb wall.

// ── parameters (the app's sliders; the annotations make this file
//    a configurator — openscad customizer, makerlab, anything)
/* [Case] */
wall_thickness = 3;   // [1.6:0.2:5] side walls (below 1.6 gets floppy)
base_thickness = 2.4;   // [1.6:0.2:6] case floor
case_margin    = 1.6;     // [0.2:0.1:3] pcb edge to inner wall (print tolerance)
corner_radius  = 4;    // [0:0.5:15] outer corner radius
front_height   = 7.2;     // [5:1:30] wall height, usb edge
rear_height    = 7.2;     // [5:1:30] wall height, far edge
standoff_height = 5;  // [4.5:0.5:12] pcb floats above the floor (xiao stack needs 4.3)
/* [Mounting] */
screw_size     = 2.2;    // [2:0.1:3.2] drill (m2 = 2.2, m2.5 = 2.7, m3 = 3.2)
plate_thickness = 1.2;  // [1:0.1:2] switch plate (default from the board's switch records)

// ── derived from the board (regenerate the case to change these) ──
/* [Hidden] */
pcb_width      = 57.1;   // from the generated board
pcb_height     = 80.45;
pcb_thickness  = 1.6;    // 2-layer, 1.6mm fr4
pcb_corner_radius = 2.5;
$fn = 48;
usb_slot_width  = 10.6;   // usb-c shell from the mcu record + clearance
usb_slot_z     = [2.54, 7];
usb_slot_along = 0;   // usb-c center along the front (+y) wall
screw_hole     = screw_size + 0.2;
standoff_radius = screw_size / 2 + 2.5;

// rounded rectangle, hull of four circles — no libraries needed
module rounded_rect(width, depth, radius) {
  r = max(radius, 0.01);
  hull()
    for (x = [-(width / 2 - r), width / 2 - r])
      for (y = [-(depth / 2 - r), depth / 2 - r])
        translate([x, y, 0]) circle(r);
}

cavity_width  = pcb_width + 2 * case_margin;
cavity_height = pcb_height + 2 * case_margin;
outer_width   = cavity_width + 2 * wall_thickness;
outer_height  = cavity_height + 2 * wall_thickness;
wall_height   = max(front_height, rear_height);

// the tray: floor + walls, hollow above the floor, open top
module case_body() {
  difference() {
    linear_extrude(wall_height)
      rounded_rect(outer_width, outer_height, corner_radius);
    translate([0, 0, base_thickness])
      linear_extrude(wall_height)
        rounded_rect(cavity_width, cavity_height, corner_radius - wall_thickness);
  }
}

// pcb anchors: posts under the board's mounting holes
module standoff(x, y) {
  translate([x, y, base_thickness])
    difference() {
      cylinder(h = standoff_height, r = standoff_radius);
      translate([0, 0, -1]) cylinder(h = standoff_height + 2, r = screw_hole / 2);
    }
}
module standoffs() {
  standoff(-25.05, -36.72);  // H1
  standoff(25.05, -36.72);  // H2
  standoff(-25.05, 36.73);  // H3
  standoff(25.05, 36.73);  // H4
}

// usb-c slot, cut through the front (+y) wall
module usb_slot() {
  translate([usb_slot_along - usb_slot_width / 2, cavity_height / 2 - 1, usb_slot_z[0] - 0.5])
    cube([usb_slot_width, wall_thickness + 2, usb_slot_z[1] - usb_slot_z[0] + 1]);
}

module case_bottom() {
  difference() {
    union() {
      case_body();
      standoffs();
    }
    usb_slot();
  }
}

// the switch plate: sits on the wall tops, keys + knobs + display poke through
module top_plate() {
  difference() {
    linear_extrude(plate_thickness)
      rounded_rect(outer_width, outer_height, corner_radius);
    translate([-25.95, -37.62, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW1 (Kailh Choc v1 low-profile switch)
    translate([-6.9, -37.62, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW2 (Kailh Choc v1 low-profile switch)
    translate([12.15, -37.62, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW3 (Kailh Choc v1 low-profile switch)
    translate([-25.95, -18.57, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW4 (Kailh Choc v1 low-profile switch)
    translate([-6.9, -18.57, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW5 (Kailh Choc v1 low-profile switch)
    translate([12.15, -18.57, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW6 (Kailh Choc v1 low-profile switch)
    translate([-25.95, 0.47, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW7 (Kailh Choc v1 low-profile switch)
    translate([-6.9, 0.47, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW8 (Kailh Choc v1 low-profile switch)
    translate([12.15, 0.47, -1])
      cube([13.8, 13.8, plate_thickness + 2]);  // SW9 (Kailh Choc v1 low-profile switch)
    translate([-25.05, -36.72, -1])
      cylinder(h = plate_thickness + 2, d = screw_hole);  // H1
    translate([25.05, -36.72, -1])
      cylinder(h = plate_thickness + 2, d = screw_hole);  // H2
    translate([-25.05, 36.73, -1])
      cylinder(h = plate_thickness + 2, d = screw_hole);  // H3
    translate([25.05, 36.73, -1])
      cylinder(h = plate_thickness + 2, d = screw_hole);  // H4
  }
}

// ── parts: print both, they sit side by side in this render ──────
case_bottom();
translate([outer_width / 2 + 15, 0, 0]) top_plate();
