/** the caps engine — flow 05. caps are the LAST projection of the component
 *  records (see component-geometry-pipeline.md): the switch record says the
 *  family, the cell says the row, the profile says the rest. deterministic
 *  openscad codegen, customizer-annotated like the case engine — every cap
 *  set is a configurator (makerlab pattern: "just drag a slider").
 *  geometry sources + license notes: research/notes/flow-05-caps-and-viz.md */
import type { PcbResult, Placement } from "../../../circuitron/src/types.ts";
import { FOOTPRINTS } from "../../../circuitron/src/footprints.ts";
import { CAP_PROFILES, DEFAULT_PROFILE, KeycapProfile } from "./profiles.ts";

export interface CapsOptions {
  /** keycap profile id (see profiles.ts) */
  profile: string;
  /** cap wall thickness, mm */
  wall: number;
  /** gap between cap and its neighbors, mm */
  capGap: number;
  /** knob diameter, mm */
  knobDiameter: number;
  /** knob height above plate, mm */
  knobHeight: number;
  /** knob d-shaft bore, mm (EC11 d-shaft) */
  knobBore: number;
  /** dish style override multiplier */
  dishScale: number;
}

export const DEFAULT_CAPS_OPTIONS: CapsOptions = {
  profile: DEFAULT_PROFILE,
  wall: 1.5,
  capGap: 0.5,
  knobDiameter: 22,
  knobHeight: 14,
  knobBore: 6.2, // common EC11 d-shaft spec — TODO verify against the ec11 datasheet before production
  dishScale: 1.0,
};

export interface CapsWarning {
  level: "warning" | "error";
  message: string;
}

export interface CapsResult {
  scad: string;
  warnings: CapsWarning[];
  stats: { caps: number; knobs: number; profile: string };
}

const REC = (p: Placement) => FOOTPRINTS[p.library];
const fmt = (n: number) => Number(n.toFixed(3)).toString();
const f = (n: number) => Number.isInteger(n) ? `${n}` : fmt(n);

export function generateCaps(pcb: PcbResult, partial?: Partial<CapsOptions>): CapsResult {
  const opts = { ...DEFAULT_CAPS_OPTIONS, ...partial };
  const warnings: CapsWarning[] = [];

  const keys = pcb.placements.filter((p) => REC(p)?.category === "switch");
  const encoders = pcb.placements.filter((p) => REC(p)?.category === "encoder");

  const profile = CAP_PROFILES.find((p) => p.id === opts.profile);
  if (!profile) {
    return {
      scad: "",
      warnings: [{ level: "error", message: `unknown cap profile "${opts.profile}" — known: ${CAP_PROFILES.map((p) => p.id).join(", ")}` }],
      stats: { caps: 0, knobs: 0, profile: opts.profile },
    };
  }

  for (const k of keys) {
    const cell = k.cellRef;
    const row = cell?.row ?? 2;
    if (row > 4) warnings.push({ level: "warning", message: `${k.ref} is on grid row ${row} — cap row tilts only cover R1–R5, clamping to R5` });
    if (k.library.includes("Choc")) {
      warnings.push({ level: "warning", message: `${k.ref} is a choc switch — choc cap stems land with the choc flow; its cap renders with an mx cross stem for now` });
    }
  }

  const L: string[] = [];
  L.push(`// keeberia caps — ${pcb.boardName} — flow 05`);
  L.push(`// generated by the caps engine; edit the sliders, not the geometry`);
  L.push(`// cap positions/rows derive from THIS board's pcb (regenerate to change them)`);
  L.push(``);
  L.push(`/* [Caps] */`);
  L.push(`// keycap profile for every cap on the board`);
  L.push(`profile_id = "${profile.id}"; // [${CAP_PROFILES.map((p) => `${p.id}:${p.name}`).join(", ")}]`);
  L.push(`// cap wall thickness, mm`);
  L.push(`wall = ${f(opts.wall)};  // [1:0.1:2.5]`);
  L.push(`// gap between neighboring caps, mm`);
  L.push(`cap_gap = ${f(opts.capGap)};  // [0.2:0.1:1]`);
  L.push(`// dish depth multiplier (1 = profile spec)`);
  L.push(`dish_scale = ${f(opts.dishScale)};  // [0.5:0.1:2]`);
  L.push(`/* [Knob] */`);
  L.push(`// knob diameter, mm`);
  L.push(`knob_d = ${f(opts.knobDiameter)};  // [16:1:30]`);
  L.push(`// knob height above the plate, mm`);
  L.push(`knob_h = ${f(opts.knobHeight)};  // [8:1:24]`);
  L.push(`// d-shaft bore diameter, mm`);
  L.push(`knob_bore = ${f(opts.knobBore)};  // [5.5:0.1:7]`);
  L.push(``);
  L.push(`/* [Hidden] */`);
  L.push(`$fn = 48;`);
  // the profile table — data from profiles.ts, provenance in the repo
  for (const p of CAP_PROFILES) {
    L.push(`// ${p.id}: ${p.source}`);
  }
  L.push(`profiles = [`);
  for (const p of CAP_PROFILES) {
    L.push(`  ["${p.id}", ${f(p.base)}, ${f(p.taper)}, ${f(p.height)}, ${f(p.dish)}, [${p.tilts.map(f).join(", ")}]],`);
  }
  L.push(`];`);
  L.push(`function prof(id) = [for (p = profiles) if (p[0] == id) p][0];`);
  L.push(`prof_v = prof(profile_id);`);
  L.push(`// [x, y, unit_span, row] per cap — from the pcb placements`);
  L.push(`caps = [`);
  for (const k of keys) {
    const unit = k.cellRef?.colSpan ?? 1;
    const row = k.cellRef?.row ?? 2;
    L.push(`  [${f(k.pos.x)}, ${f(k.pos.y)}, ${f(unit)}, ${f(row)}],  // ${k.ref}`);
  }
  L.push(`];`);
  L.push(`knobs = [`);
  for (const e of encoders) {
    L.push(`  [${f(e.pos.x)}, ${f(e.pos.y)}],  // ${e.ref}`);
  }
  L.push(`];`);

  // ── the cap module ──
  L.push(`
module rbox2d(w, d, r) {
  offset(r) offset(-r) square([w, d], center = true);
}

// one keycap: tapered hollow body, spherical dish, mx cross stem
module keycap(unit, row) {
  base_w = prof_v[1] * unit - cap_gap;
  top_w = base_w * prof_v[2];
  h = prof_v[3];
  dish = prof_v[4] * dish_scale;
  tilt = prof_v[5][min(row, 4)];
  wall_v = wall;
  difference() {
    // body: hull from the base square to the tilted top square
    hull() {
      linear_extrude(0.01) rbox2d(base_w, base_w, 1.2);
      translate([0, 0, h]) rotate([tilt, 0, 0]) linear_extrude(0.01) rbox2d(top_w, top_w, 1.0);
    }
    // hollow inside: same hull, shrunk by the wall
    translate([0, 0, wall_v]) hull() {
      translate([0, 0, -wall_v]) linear_extrude(0.01) rbox2d(base_w - 2 * wall_v, base_w - 2 * wall_v, 1.0);
      translate([0, 0, h - wall_v]) rotate([tilt, 0, 0]) linear_extrude(0.01) rbox2d(top_w - 2 * wall_v, top_w - 2 * wall_v, 0.8);
    }
    // dish: sphere carved into the tilted top
    translate([0, -top_w * sin(tilt) / 4, h + 24.2 - dish]) rotate([tilt, 0, 0]) sphere(24);
  }
  // mx cross stem socket, inside the cap: ring + cross void + wall bridges
  // (4.1mm cross standard; insertion depth + tolerance pattern from
  // keycap_playground stem defaults)
  cross_w = 4.1;
  cross_t = 1.2;
  depth = 4;
  tol = 0.2;
  difference() {
    cylinder(h = depth, d = 5.6);
    translate([0, 0, -0.5]) union() {
      cube([cross_w - 2 * tol, cross_t - 2 * tol, depth + 1.2], center = true);
      cube([cross_t - 2 * tol, cross_w - 2 * tol, depth + 1.2], center = true);
    }
  }
  // bridges: tie the stem ring to the inner cap walls so it prints
  bridge_len = (base_w - 2 * wall_v) / 2;
  for (ang = [0, 90, 180, 270]) {
    rotate([0, 0, ang]) translate([2.0, -0.4, depth / 2]) cube([bridge_len, 0.8, 0.8]);
  }
}

// knob cover: ridged cylinder with a d-shaft bore
module knob() {
  difference() {
    union() {
      cylinder(h = knob_h, d1 = knob_d, d2 = knob_d - 3);
      for (i = [0 : 24]) {
        rotate([0, 0, i * 15]) translate([(knob_d - 1.8) / 2, 0, 1.2]) cube([1.4, 2.2, knob_h - 2.4]);
      }
    }
    translate([0, 0, -0.5]) {
      cylinder(h = knob_h - 2.5, d = knob_bore);
      translate([0, -knob_bore / 2 - 0.2, 0]) cube([knob_bore / 2 + 0.2, knob_bore + 0.4, knob_h - 2.5]);
    }
  }
}

for (c = caps) {
  translate([c[0], c[1], 0]) keycap(c[2], c[3]);
}
for (k = knobs) {
  translate([k[0], k[1], 0]) knob();
}`);

  return {
    scad: L.join("\n"),
    warnings,
    stats: { caps: keys.length, knobs: encoders.length, profile: profile.id },
  };
}
